/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Config.KoneksiDatabase;

/**
 *
 * @author ACER A5145433WF
 */
public class TIketCostumer extends javax.swing.JFrame {
    KoneksiDatabase myObject;
    /**
     * Creates new form TIketCostumer
     */
    public DefaultTableModel modelTabelTiketCostumer;
    public TIketCostumer() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        myObject = new KoneksiDatabase();
        modelTabelTiketCostumer = new DefaultTableModel();
        tblData.setModel(modelTabelTiketCostumer);
        modelTabelTiketCostumer.addColumn("NIK");
        modelTabelTiketCostumer.addColumn("Nama");
        modelTabelTiketCostumer.addColumn("Jenis Kelamin");
        modelTabelTiketCostumer.addColumn("Alamat");
        modelTabelTiketCostumer.addColumn("No Telpon");
        modelTabelTiketCostumer.addColumn("Kelas");
        modelTabelTiketCostumer.addColumn("Maskapai");
        modelTabelTiketCostumer.addColumn("Keberangkatan");
        modelTabelTiketCostumer.addColumn("Tujuan");
        modelTabelTiketCostumer.addColumn("Tanggal");
        modelTabelTiketCostumer.addColumn("Jam");
        modelTabelTiketCostumer.addColumn("Biaya");
        tampilDataTiketCostumer();
    }

    public void tampilDataTiketCostumer(){
        try {
            modelTabelTiketCostumer.getDataVector().removeAllElements();
            modelTabelTiketCostumer.fireTableDataChanged();
        
            PreparedStatement query = myObject.Konek.prepareStatement("SELECT * FROM tb_tiketcostumer");
            ResultSet data = query.executeQuery();
            while (data.next()) {
            Object[] baris = new Object[12];
            baris[0] = data.getString("nik");
            baris[1] = data.getString("nama");
            baris[2] = data.getString("jenis_kelamin");
            baris[3] = data.getString("alamat");
            baris[4] = data.getString("no_telpon");
            baris[5] = data.getString("kelas");
            baris[6] = data.getString("maskapai");
            baris[7] = data.getString("keberangkatan");
            baris[8] = data.getString("tujuan");
            baris[9] = data.getString("tanggal");
            baris[10] = data.getString("jam");
            baris[11] = data.getString("biaya");
            modelTabelTiketCostumer.addRow(baris);
            
            }
            query.close();
            data.close();
            } catch (Exception e){
            }
        
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbxJK = new javax.swing.JComboBox<>();
        cbxKelas = new javax.swing.JComboBox<>();
        cbxMaskapai = new javax.swing.JComboBox<>();
        tfNIK = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfAlamat = new javax.swing.JTextField();
        tfNotelpon = new javax.swing.JTextField();
        tfKeberangkatan = new javax.swing.JTextField();
        tfTujuan = new javax.swing.JTextField();
        tfTanggal = new javax.swing.JTextField();
        tfJam = new javax.swing.JTextField();
        tfBiaya = new javax.swing.JTextField();
        buttonSimpan = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pemesanan Tiket Costumer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(51, 0, 51))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("TIKET COSTUMER");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("NIK");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Jenis Kelamin");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Alamat");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("No Telpon");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("Kelas");

        jScrollPane1.setForeground(new java.awt.Color(51, 0, 51));

        tblData.setBackground(new java.awt.Color(255, 255, 255));
        tblData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblData.setForeground(new java.awt.Color(51, 0, 51));
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("Makapai");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 51));
        jLabel9.setText("Keberangkatan");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("Tujuan");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 51));
        jLabel11.setText("Tanggal");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 51));
        jLabel12.setText("Jam");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 51));
        jLabel13.setText("Biaya");

        cbxJK.setBackground(new java.awt.Color(255, 255, 255));
        cbxJK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxJK.setForeground(new java.awt.Color(51, 0, 51));
        cbxJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Laki - Laki", "Perempuan" }));

        cbxKelas.setBackground(new java.awt.Color(255, 255, 255));
        cbxKelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxKelas.setForeground(new java.awt.Color(51, 0, 51));
        cbxKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Ekonomi", "Bisnis", "Pemerintah" }));

        cbxMaskapai.setBackground(new java.awt.Color(255, 255, 255));
        cbxMaskapai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxMaskapai.setForeground(new java.awt.Color(51, 0, 51));
        cbxMaskapai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Wings Air", "Lion Air", "Sriwijaya Air", "Garuda Indonesia", "NAM Air", "Batik Air", "Citilink", " " }));

        tfNIK.setBackground(new java.awt.Color(255, 255, 255));
        tfNIK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfNIK.setForeground(new java.awt.Color(51, 0, 51));

        tfNama.setBackground(new java.awt.Color(255, 255, 255));
        tfNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfNama.setForeground(new java.awt.Color(51, 0, 51));

        tfAlamat.setBackground(new java.awt.Color(255, 255, 255));
        tfAlamat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfAlamat.setForeground(new java.awt.Color(51, 0, 51));

        tfNotelpon.setBackground(new java.awt.Color(255, 255, 255));
        tfNotelpon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfNotelpon.setForeground(new java.awt.Color(51, 0, 51));

        tfKeberangkatan.setBackground(new java.awt.Color(255, 255, 255));
        tfKeberangkatan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfKeberangkatan.setForeground(new java.awt.Color(51, 0, 51));

        tfTujuan.setBackground(new java.awt.Color(255, 255, 255));
        tfTujuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfTujuan.setForeground(new java.awt.Color(51, 0, 51));

        tfTanggal.setBackground(new java.awt.Color(255, 255, 255));
        tfTanggal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfTanggal.setForeground(new java.awt.Color(51, 0, 51));

        tfJam.setBackground(new java.awt.Color(255, 255, 255));
        tfJam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfJam.setForeground(new java.awt.Color(51, 0, 51));

        tfBiaya.setBackground(new java.awt.Color(255, 255, 255));
        tfBiaya.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfBiaya.setForeground(new java.awt.Color(51, 0, 51));

        buttonSimpan.setBackground(new java.awt.Color(255, 255, 255));
        buttonSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSimpan.setForeground(new java.awt.Color(51, 0, 51));
        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonUbah.setBackground(new java.awt.Color(255, 255, 255));
        buttonUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonUbah.setForeground(new java.awt.Color(51, 0, 51));
        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        buttonHapus.setBackground(new java.awt.Color(255, 255, 255));
        buttonHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonHapus.setForeground(new java.awt.Color(51, 0, 51));
        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonKembali.setBackground(new java.awt.Color(255, 255, 255));
        buttonKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKembali.setForeground(new java.awt.Color(51, 0, 51));
        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxJK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxKelas, 0, 170, Short.MAX_VALUE)
                            .addComponent(tfNIK)
                            .addComponent(tfNama)
                            .addComponent(tfAlamat)
                            .addComponent(tfNotelpon))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxMaskapai, 0, 165, Short.MAX_VALUE)
                            .addComponent(tfKeberangkatan)
                            .addComponent(tfTujuan)
                            .addComponent(tfTanggal)
                            .addComponent(tfJam)
                            .addComponent(tfBiaya))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonHapus)
                            .addComponent(buttonKembali)
                            .addComponent(buttonUbah)
                            .addComponent(buttonSimpan))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfNotelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbxKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbxMaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(buttonSimpan)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfKeberangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonUbah))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonHapus)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tfJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tfBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonKembali))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        //button simpan buat menyimpan data
        try {
            
            if (tfNIK.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID belum di isi");
                tfNIK.requestFocus();
         
            }else{
                String sql = "insert into tb_tiketcostumer value ('"+tfNIK.getText()+"','"+tfNama.getText()+"','"+cbxJK.getSelectedItem()+"','"+tfAlamat.getText()+"','"+tfNotelpon.getText()+"','"+cbxKelas.getSelectedItem()+"','"+cbxMaskapai.getSelectedItem()+"','"+tfKeberangkatan.getText()+"','"+tfTujuan.getText()+"','"+tfTanggal.getText()+"','"+tfJam.getText()+"','"+tfBiaya.getText()+"')";
                myObject.Konek.createStatement().execute(sql);
                tampilDataTiketCostumer();
                JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }                                             

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        System.exit(0);
    
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        // TODO add your handling code here:
         // untuk edit data
        try {
    if (tfNIK.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "ID belum di isi");
        tfNIK.requestFocus();
    } else {
        String sql = "UPDATE tb_tiketcostumer SET nama = ?, jenis_kelamin = ?, alamat = ?, no_telpon = ?, kelas = ?, maskapai = ?, keberangkatan = ?, tujuan = ?, tanggal = ?, jam = ?, biaya = ? WHERE NIK = ?";
        
        PreparedStatement preparedStatement = myObject.Konek.prepareStatement(sql);
        preparedStatement.setString(1, tfNama.getText());
        preparedStatement.setString(2, cbxJK.getSelectedItem().toString());
        preparedStatement.setString(3, tfAlamat.getText());
        preparedStatement.setString(4, tfNotelpon.getText());
        preparedStatement.setString(5, cbxKelas.getSelectedItem().toString());
        preparedStatement.setString(6, cbxMaskapai.getSelectedItem().toString());
        preparedStatement.setString(7, tfKeberangkatan.getText());
        preparedStatement.setString(8, tfTujuan.getText());
        preparedStatement.setString(9, tfTanggal.getText());
        preparedStatement.setString(10, tfJam.getText());
        preparedStatement.setString(11, tfBiaya.getText());
        preparedStatement.setString(12, tfNIK.getText());
        
        int rowsUpdated = preparedStatement.executeUpdate();
        
        if (rowsUpdated > 0) {
            tampilDataTiketCostumer();
            JOptionPane.showMessageDialog(this, "Data dengan ID " + tfNIK.getText() + " berhasil diubah");
        } else {
            JOptionPane.showMessageDialog(this, "Tidak ada data dengan ID " + tfNIK.getText());
        }
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
}

    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
         // untuk menghapus data
        try {
    if (tfNIK.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "NIK belum di isi");
        tfNIK.requestFocus();
    } else {
        String sql = "DELETE FROM tb_tiketcostumer WHERE nik=?";
        try (PreparedStatement preparedStatement = myObject.Konek.prepareStatement(sql)) {
            preparedStatement.setString(1, tfNIK.getText());

            int rowsDeleted = preparedStatement.executeUpdate();

            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                tampilDataTiketCostumer();
            } else {
                JOptionPane.showMessageDialog(this, "Tidak ada data dengan NIK tersebut");
            }
        }
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.toString());
}
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        String nik = tblData.getValueAt(baris, 0).toString();
        String nama = tblData.getValueAt(baris, 1).toString();
        String alamat = tblData.getValueAt(baris, 3).toString();
        String no_telpon = tblData.getValueAt(baris, 4).toString();
        String keberangkatan = tblData.getValueAt(baris, 7).toString();
        String tujuan = tblData.getValueAt(baris, 8).toString();
        String tanggal = tblData.getValueAt(baris, 9).toString();
        String jam = tblData.getValueAt(baris, 10).toString();
        String biaya = tblData.getValueAt(baris, 11).toString();
        tfNIK.setText(nik);
        tfNama.setText(nama);
        tfAlamat.setText(alamat);
        tfAlamat.setText(alamat);
        tfNotelpon.setText(no_telpon);
        tfKeberangkatan.setText(keberangkatan);
        tfTujuan.setText(tujuan);
        tfTanggal.setText(tanggal);
        tfJam.setText(jam);
        tfBiaya.setText(biaya);
    }//GEN-LAST:event_tblDataMouseClicked

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TIketCostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TIketCostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TIketCostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TIketCostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TIketCostumer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JComboBox<String> cbxJK;
    private javax.swing.JComboBox<String> cbxKelas;
    private javax.swing.JComboBox<String> cbxMaskapai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfBiaya;
    private javax.swing.JTextField tfJam;
    private javax.swing.JTextField tfKeberangkatan;
    private javax.swing.JTextField tfNIK;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNotelpon;
    private javax.swing.JTextField tfTanggal;
    private javax.swing.JTextField tfTujuan;
    // End of variables declaration//GEN-END:variables
}
